/*
 * Copyright 2008 DataBaseMetaDataConverter.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package code.google.com.dbmetadataconverter.model;

import java.util.ArrayList;
import java.util.List;

public class Table implements Comparable<Table>{
	
	private String name;
	private List<Field> fields = new ArrayList<Field>();
	private List<Field> keys = new ArrayList<Field>(3);
	private List<Relation> pkRelations = new ArrayList<Relation>(3);
	private List<Relation> fkRelations = new ArrayList<Relation>(3);
	private boolean keyAutoInc;
	private String nameForClass;
	private String nameForAttribute;
	private String sequenceName;
	
	public Table() {
		
	}
	
	public Table(String name) {
		this.name = name;
	}
	
	/**
	 * Returns all the fields from this table.
	 * @return
	 */
	public List<Field> getFields() {
		return fields;
	}
	
	public void setFields(List<Field> fields) {
		this.fields = fields;
	}
	
	/**
	 * Returns the fields of this table that belongs to the primary key.
	 * @return
	 */
	public List<Field> getKeys() {
		return keys;
	}
	
	public void setKeys(List<Field> chaves) {
		this.keys = chaves;
	}
	
	/**
	 * Returns true if this table has only one key and it is auto incremental / identity.
	 * @return
	 */
	public boolean isKeyAutoInc() {
		return keyAutoInc;
	}
	
	public void setKeyAutoInc(boolean keyAutoInc) {
		this.keyAutoInc = keyAutoInc;
	}
	
	/**
	 * Returns the name of the table. This name is the same one that is on the database.
	 * @return
	 */
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	/**
	 * Compares the table by the name of the table.
	 * @return
	 */
	public boolean equals(Object o) {
		if (o == null || !(o instanceof Table)) return false;
		return ((Table)o).name.equals(name);
	}
	
	/**
	 * Compares one table to another. Returns 0 if they are equals. 
	 * The result is positive if this table is grater then the parameter table or negative
	 * if the parameter table is grater. 
	 */
	@Override
	public int compareTo(Table o) {		
		return name.compareTo(o.name);
	}

	/**
	 * Returns the relations of this table where it exports the fields (is the primary key table).
	 * @return
	 */
	public List<Relation> getPkRelations() {
		return pkRelations;
	}

	public void setPkRelations(List<Relation> pkRelations) {
		this.pkRelations = pkRelations;
	}

	/**
	 * Returns the relations of this table where it imports the fields (is the foreign key table).
	 * @return
	 */
	public List<Relation> getFkRelations() {
		return fkRelations;
	}

	public void setFkRelations(List<Relation> fkRelations) {
		this.fkRelations = fkRelations;
	}

	/**
	 * Returns the name of the table converted to the java code conventions definition
	 * for classes names. Ex: test_field becomes TestField.
	 * @return
	 */
	public String getNameForClass() {
		return nameForClass;
	}

	public void setNameForClass(String nameForClass) {
		this.nameForClass = nameForClass;
	}

	/**
	 * Returns the name of the table converted to the java code conventions definition
	 * for attributes variables. Ex: test_field becomes testField.
	 * @return
	 */
	public String getNameForAttribute() {
		return nameForAttribute;
	}

	public void setNameForAttribute(String nameForAttribute) {
		this.nameForAttribute = nameForAttribute;
	}

	/**
	 * If this table has an id generated by a sequence, this method returns the sequence name. 
	 * It returns null otherwise.
	 * @return
	 */
	public String getSequenceName() {
		return sequenceName;
	}

	public void setSequenceName(String sequenceName) {
		this.sequenceName = sequenceName;
	}
}
